on: pull_request

jobs:
  lint:
    runs-on: ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install

      - name: Lint
        run: npm run lint

  check-style:
    runs-on: ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm install

      - name: Check style
        run: npm run checkstyle
